set_property IOSTANDARD PCI33_3 [get_ports {dina[5]}]
set_property IOSTANDARD PCI33_3 [get_ports {dina[4]}]
set_property IOSTANDARD PCI33_3 [get_ports {dina[3]}]
set_property IOSTANDARD PCI33_3 [get_ports {dina[2]}]
set_property IOSTANDARD PCI33_3 [get_ports {dina[1]}]
set_property IOSTANDARD PCI33_3 [get_ports {dina[0]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[5]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[4]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[3]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[2]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[1]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[0]}]
set_property IOSTANDARD PCI33_3 [get_ports sys_clk_p]
set_property IOSTANDARD PCI33_3 [get_ports sys_clk_n]
set_property IOSTANDARD PCI33_3 [get_ports reset]
set_property IOSTANDARD PCI33_3 [get_ports {addra[14]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[13]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[12]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[11]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[10]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[9]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[8]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[7]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[6]}]
set_property IOSTANDARD PCI33_3 [get_ports {addra[15]}]
set_property IOSTANDARD PCI33_3 [get_ports {douta[5]}]
set_property IOSTANDARD PCI33_3 [get_ports {douta[3]}]
set_property IOSTANDARD PCI33_3 [get_ports {douta[4]}]
set_property IOSTANDARD PCI33_3 [get_ports {douta[2]}]
set_property IOSTANDARD PCI33_3 [get_ports {douta[1]}]
set_property IOSTANDARD PCI33_3 [get_ports {douta[0]}]
set_property IOSTANDARD PCI33_3 [get_ports {douta[6]}]
set_property IOSTANDARD PCI33_3 [get_ports {douta[7]}]
set_property IOSTANDARD PCI33_3 [get_ports {dina[6]}]
set_property IOSTANDARD PCI33_3 [get_ports {dina[7]}]

set_property PACKAGE_PIN B1 [get_ports {addra[15]}]
set_property PACKAGE_PIN A3 [get_ports {dina[7]}]
set_property PACKAGE_PIN A4 [get_ports {dina[6]}]
set_property PACKAGE_PIN A5 [get_ports {dina[5]}]
set_property PACKAGE_PIN A6 [get_ports {dina[4]}]
set_property PACKAGE_PIN A8 [get_ports {dina[3]}]
set_property PACKAGE_PIN A9 [get_ports {dina[2]}]
set_property PACKAGE_PIN A10 [get_ports {dina[1]}]
set_property PACKAGE_PIN A11 [get_ports {dina[0]}]
set_property PACKAGE_PIN B2 [get_ports {addra[14]}]
set_property PACKAGE_PIN B3 [get_ports {addra[13]}]
set_property PACKAGE_PIN B4 [get_ports {addra[12]}]
set_property PACKAGE_PIN B6 [get_ports {addra[11]}]
set_property PACKAGE_PIN B7 [get_ports {addra[10]}]
set_property PACKAGE_PIN B8 [get_ports {addra[9]}]
set_property PACKAGE_PIN B9 [get_ports {addra[8]}]
set_property PACKAGE_PIN B11 [get_ports {addra[7]}]
set_property PACKAGE_PIN B12 [get_ports {addra[6]}]
set_property PACKAGE_PIN B13 [get_ports {addra[5]}]
set_property PACKAGE_PIN B14 [get_ports {addra[4]}]
set_property PACKAGE_PIN B16 [get_ports {addra[3]}]
set_property PACKAGE_PIN B17 [get_ports {addra[2]}]
set_property PACKAGE_PIN B18 [get_ports {addra[1]}]
set_property PACKAGE_PIN C1 [get_ports {addra[0]}]
set_property PACKAGE_PIN V17 [get_ports {douta[0]}]
set_property PACKAGE_PIN V16 [get_ports {douta[1]}]
set_property PACKAGE_PIN V15 [get_ports {douta[2]}]
set_property PACKAGE_PIN V14 [get_ports {douta[3]}]
set_property PACKAGE_PIN V12 [get_ports {douta[4]}]
set_property PACKAGE_PIN V11 [get_ports {douta[5]}]
set_property PACKAGE_PIN V10 [get_ports {douta[6]}]
set_property PACKAGE_PIN V9 [get_ports {douta[7]}]

create_clock -period 10.000 -name sys_clk_p -waveform {2.000 8.000} -add [get_ports sys_clk_p]
set_input_delay -clock [get_clocks sys_clk_p] -min -add_delay 2.000 [get_ports {addra[*]}]
set_input_delay -clock [get_clocks sys_clk_p] -max -add_delay 2.000 [get_ports {addra[*]}]
set_input_delay -clock [get_clocks sys_clk_p] -min -add_delay 1.000 [get_ports {dina[*]}]
set_input_delay -clock [get_clocks sys_clk_p] -max -add_delay 1.000 [get_ports {dina[*]}]
set_output_delay -clock [get_clocks sys_clk_p] -min -add_delay 0.000 [get_ports {douta[*]}]
set_output_delay -clock [get_clocks sys_clk_p] -max -add_delay 1.000 [get_ports {douta[*]}]

set_property MARK_DEBUG false [get_nets sys_clk_p]
